name: Deploy CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/

      - name: Check installing dependencies
        run: |
          ls -al
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github".insteadOf https://github
          yarn add "git+https://github.com/gitgitWi/chartiq-8.6.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      # - name: Deploy to Vercel
      #   run: |
      #     prodRun=""
      #     if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
      #       prodRun="--prod"
      #     fi
      #     npx vercel --token ${VERCEL_TOKEN} $prodRun
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
